/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8025b5bb-6215-4063-bed9-1751d778b6c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nwThyBmag",
    "aws_user_pools_web_client_id": "4p0gbjcsb1qit6ld5i0qvee2gb",
    "oauth": {}
};


export default awsmobile;
